default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/reservations_development.sqlite3

test:
  <<: *default
  database: db/reservations_test.sqlite3

production:
  <<: *default
  database: db/reservations_production.sqlite3
